# Jekyll site configuration file
# -----------------------------------------------------------------------------
# When changes are made to this file, github will rebuild your site.
# This takes about 10 minutes.

# Set a site title (this will appear in the browser title bar)

title: Tech Meet-ups

# Set a name and description for the main page of your site.

name: Awesome Tech Meet-ups
description: All tech, all awesome, all the time.

# Site themes by: twitter bootstrap and bootswatch.com.
# Go to: http://bootswatch.com/ for theme previews.
# Options: amelia, cerulean, cosmo, cyborg, default, flatly, journal, 
# readable, simplex, slate, spacelab, spruce, superhero, and united.

theme: spacelab

# Set your github and twitter username for user throughout the site.

twitter-username: TechUpHQ
github-username: TechUpHQ

# Do you want to blog on your site? If so, set this to true.
# Next, you will have to create a new blog entry in the _posts directory.
# See the example file in that directory for details.

blog-enabled: true

# Do you want a photo gallery on your site? If so, set this to true.
# This feature requires you to upload your photos to Picasa.
# Set you picasa user id and all your public albums will be displayed.

photo-gallery-enabled: true
picasa-user-id: 106930217921539674382

# Pygments allows for code syntax highlighting. All of the built-in
# themes are included as css files. Just specify the name of the theme
# you want to use.
# Thanks to: https://github.com/richleland/pygments-css for the css files.
# Look in the css/pygments directory for all the options.

pygments: true
pygments-theme: zenburn
